config/routes.rb
Spree::Core::Engine.routes.draw do

  get "/wholesaler/states" => "spree/wholesaler_states#index"

  resources :wholesalers

  namespace(:admin) do

    resources :wholesalers do
      member do
        get :approve
        get :reject
      end
    end

  end

end

app/models/spree/wholesaler.rb
class Spree::Wholesaler < ActiveRecord::Base
  partial_updates = false

  belongs_to :user, :class_name => "Spree::User"
  belongs_to :bill_address, :foreign_key => "billing_address_id", :class_name => "Spree::Address", :dependent => :destroy
  belongs_to :ship_address, :foreign_key => "shipping_address_id", :class_name => "Spree::Address", :dependent => :destroy

  accepts_nested_attributes_for :bill_address
  accepts_nested_attributes_for :ship_address
  accepts_nested_attributes_for :user

  attr_accessor :use_billing
  before_validation :clone_billing_address, :if => :use_billing
  validates :company, :buyer_contact, :manager_contact, :phone, :taxid, :presence => true

  delegate :spree_roles, to: :user
  delegate :email, to: :user

  def activate!
    get_wholesale_role
    return false if user.spree_roles.include?(@role)
    user.spree_roles << @role
    user.save
  end

  def deactivate!
    get_wholesale_role
    return false unless user.spree_roles.include?(@role)
    user.spree_roles.delete(@role)
    user.save
  end

  def active?
    user && user.has_spree_role?("wholesaler")
  end

  def self.term_options
    %(Net 10, Net 15, Net 30, COD, Credit Card).split(", ")
  end

  private

  def get_wholesale_role
    @role = Spree::Role.find_or_create_by(name: "wholesaler")
  end

  def clone_billing_address
    if bill_address and self.ship_address.nil?
      self.ship_address = bill_address.clone
    else
      self.ship_address.attributes = bill_address.attributes.except("id", "updated_at", "created_at")
    end
    true
  end
end

app/controllers/spree/admin/wholesalers_controller.rb
class Spree::Admin::WholesalersController < Spree::Admin::ResourceController
  respond_to :html, :xml
  before_action :approval_setup, :only => [ :approve, :reject ]

  def index
  end

  def show
    @wholesaler = Spree::Wholesaler.find(params[:id])
    respond_with(@wholesaler)
  end

  def new
    @wholesaler = Spree::Wholesaler.new
    @wholesaler.build_user
    @wholesaler.bill_address = Spree::Address.default
    @wholesaler.ship_address = Spree::Address.default
    respond_with(@wholesaler)
  end

  def create
    @wholesaler = Spree::Wholesaler.new(wholesale_params)
    if @wholesaler.save
      flash[:notice] = I18n.t('spree.admin.wholesaler.success')
      redirect_to spree.admin_wholesalers_path
    else
      flash[:error] = I18n.t('spree.admin.wholesaler.failed')
      render :action => "new"
    end
  end

  def edit
    @wholesaler = Spree::Wholesaler.find(params[:id])
    respond_with(@wholesaler)
  end

  def update
    @wholesaler = Spree::Wholesaler.find(params[:id])

    if @wholesaler.update_attributes(wholesale_params)
      flash[:notice] = I18n.t('spree.admin.wholesaler.update_success')
    else
      flash[:error] = I18n.t('spree.admin.wholesaler.update_failed')
    end
    respond_with(@wholesaler)
  end

  def destroy
    @wholesaler = Spree::Wholesaler.find(params[:id])
    @wholesaler.destroy
    flash[:notice] = I18n.t('spree.admin.wholesaler.destroy_success')
    respond_with(@wholesaler)
  end

  def approve
    return redirect_to request.referer, :flash => { :error => "Wholesaler is already active." } if @wholesaler.active?
    @wholesaler.activate!
    redirect_to request.referer, :flash => { :notice => "Wholesaler was successfully approved." }
  end

  def reject
    return redirect_to request.referer, :flash => { :error => "Wholesaler is already rejected." } unless @wholesaler.active?
    @wholesaler.deactivate!
    redirect_to request.referer, :flash => { :notice => "Wholesaler was successfully rejected." }
  end

  private

  def approval_setup
    @wholesaler = Spree::Wholesaler.find(params[:id])
    @role = Spree::Role.find_or_create_by(name: "wholesaler")
  end

  def collection
    return @collection if @collection.present?

    params[:search] ||= {}
    params[:search][:meta_sort] ||= "company.asc"
    @search = Spree::Wholesaler.ransack(params[:q])
    @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
  end

  def wholesale_params
    params.require(:wholesaler).permit(:ship_address, :bill_address, :company, :buyer_contact, :manager_contact, :phone, :fax, :resale_number, :taxid, :web_address, :terms, :notes, :use_billing, bill_address_attributes: [:firstname, :lastname, :address1, :address2, :city, :state_id, :zipcode, :country_id, :phone], ship_address_attributes: [:firstname, :lastname, :address1, :address2, :city, :state_id, :zipcode, :country_id, :phone], user_attributes: [:email, :password, :password_confirmation])
  end

end

app/controllers/spree/wholesalers_controller.rb
class Spree::WholesalersController < Spree::BaseController
  respond_to :html, :xml

  def index
  end

  def show
    @wholesaler = Spree::Wholesaler.find(params[:id])
    respond_with(@wholesaler)
  end

  def new
    @wholesaler = Spree::Wholesaler.new
    @wholesaler.build_user
    @wholesaler.bill_address = Spree::Address.default
    @wholesaler.ship_address = Spree::Address.default
    respond_with(@wholesaler)
  end

  def create
    @wholesaler = Spree::Wholesaler.new(wholesale_params)
    if @wholesaler.save
      flash[:notice] = I18n.t('spree.wholesaler.signup_success')
      redirect_to spree.wholesalers_path
    else
      flash[:error] = I18n.t('spree.wholesaler.signup_failed')
      render :action => "new"
    end
  end

  def edit
    @wholesaler = Spree::Wholesaler.find(params[:id])
    respond_with(@wholesaler)
  end

  def update
    @wholesaler = Spree::Wholesaler.find(params[:id])

    if @wholesaler.update_attributes(wholesale_params)
      flash[:notice] = I18n.t('spree.wholesaler.update_success')
    else
      flash[:error] = I18n.t('spree.wholesaler.update_failed')
    end
    respond_with(@wholesaler)
  end

  def destroy
    @wholesaler = Spree::Wholesaler.find(params[:id])
    @wholesaler.destroy
    flash[:notice] = I18n.t('spree.wholesaler.destroy_success')
    respond_with(@wholesaler)
  end

  def wholesale_params
    params.require(:wholesaler).permit(:ship_address, :bill_address, :company, :buyer_contact, :manager_contact, :phone, :fax, :resale_number, :taxid, :web_address, :terms, :notes, :use_billing, bill_address_attributes: [:firstname, :lastname, :address1, :address2, :city, :state_id, :zipcode, :country_id, :phone], ship_address_attributes: [:firstname, :lastname, :address1, :address2, :city, :state_id, :zipcode, :country_id, :phone], user_attributes: [:email, :password, :password_confirmation])
  end

end

app/views/spree/admin/wholesalers/_form.html.erb
<% content_for :head do %>
  <script src='/states.js'></script>
<% end %>

<div class="leftie">
  <fieldset class="wholesaler-details">
    <legend>Company Information</legend>

    <p>
      <%= form.label :company %><br/>
      <%= form.text_field :company, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :buyer_contact %><br/>
      <%= form.text_field :buyer_contact, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :manager_contact %><br/>
      <%= form.text_field :manager_contact, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :phone %><br/>
      <%= form.text_field :phone, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :fax %><br/>
      <%= form.text_field :fax %>
    </p>
    <p>
      <%= form.label :resale_number %><br/>
      <%= form.text_field :resale_number %>
    </p>
    <p>
      <%= form.label :taxid %><br/>
      <%= form.text_field :taxid, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :web_address %><br/>
      <%= form.text_field :web_address %>
    </p>
    <p>
      <%= form.label :terms %><br/>
      <%= form.select :terms, Spree::Wholesaler.term_options, :class => 'required' %><span class="req">*</span>
    </p>
    <p>
      <%= form.label :notes %><br/>
      <%= form.text_area :notes %>
    </p>
  </fieldset>

  <fieldset class="user-details">
    <legend>User Details:</legend>
    <% if @wholesaler.new_record? %>
      <%= form.fields_for :user do |uf| %>
        <%= render 'spree/shared/user_form', :f => uf %>
      <% end %>
    <% else %>
      <p>
        <b>User Id:</b>
        <%= link_to @wholesaler.user.id, admin_user_path(@wholesaler.user) %>
        <br/>
        <%= link_to "view user", admin_user_path(@wholesaler.user) %> /
        <%= link_to "edit user", edit_admin_user_path(@wholesaler.user) %> /
        <%= render "user_options" %>
      </p>
    <% end %>
  </fieldset>
</div>

<div class="rightie">
  <%= render "spree/shared/address_form", :form => form %>
</div>

app/views/spree/admin/wholesalers/_user_options.html.erb
<% wholesaler ||= @wholesaler %>
<% if wholesaler.active? %>
  <%= link_to "deny", reject_admin_wholesaler_path(wholesaler) %>
<% else %>
  <%= link_to "approve", approve_admin_wholesaler_path(wholesaler) %>
<% end %>

app/views/spree/admin/wholesalers/edit.html.erb
<h1><%= t("editing_wholesaler") %></h1>

<%= form_for [:admin, @wholesaler], :html => { :class => "wholesaler-form" } do |f| %>
  <%= render "spree/shared/error_messages", :target => @wholesaler %>
  <%= render "form", :form => f %>
  <%= render "spree/admin/shared/edit_resource_links" %>
<% end %>

app/views/spree/admin/wholesalers/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <p><%= button_link_to t("new_wholesaler"), new_object_url, :icon => 'add' %></p>
    </li>
  </ul>
  <br class='clear' />
</div>


<h1><%= t("listing_wholesalers") %></h1>


<table class="index">
  <thead>
  <tr>
    <th><%= sort_link @search, :company, t('wholesaler') %></th>
    <th><%= sort_link @search, :buyer_contact, t('buyer_contact') %></th>
    <th><%= sort_link @search, :user_email, t('email') %></th>
    <th><%= sort_link @search, :phone, t('phone') %></th>
    <th><%= t('active') %></th>
    <th>
    </th>
  </tr>
  </thead>
  <tbody>
    <% @wholesalers.each do |wholesaler|%>
      <tr id="<%= dom_id wholesaler %>">
        <%- locals = {:wholesaler => wholesaler} %>
        <td><%=link_to wholesaler.company, object_url(wholesaler) %></td>
        <td><%= wholesaler.buyer_contact %></td>
        <td><%= mail_to wholesaler.email %></td>
        <td><%= wholesaler.phone %></td>
        <td width="50px"><%= wholesaler.spree_roles.include?("wholesale") ? 'yes' : 'no' %></td>
        <td>
          <%= link_to_edit wholesaler %> &nbsp;
          <%= link_to_delete wholesaler %> &nbsp;
          <%= render 'user_options', :wholesaler => wholesaler %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @wholesalers %>



<% content_for :sidebar do %>
<div class="box">
  <h3><%= t('search') %></h3>

  <% @wholesaler = Spree::Wholesaler.search %>

  <%= search_form_for [:admin, @wholesaler] do |f| %>
    <%- locals = {:f => f} %>
    <p>
      <%= t(".company") %><br />
      <%= f.text_field :company_cont, :size=>18 %>
    </p>
    <p>
      <%= t(".buyer_contact") %><br />
      <%= f.text_field :buyer_contact_cont, :size=>18 %>
    </p>
    <p>
      <%= t(".manager_contact") %><br />
      <%= f.text_field :manager_contact_cont, :size=>18 %>
    </p>
    <p>
      <%= t("phone") %><br />
      <%= f.text_field :phone_cont, :size=>18 %>
    </p>
    <p>
      <%= t(".notes") %><br />
      <%= f.text_field :notes_cont, :size=>18 %>
    </p>

    <p><%= button t("search") %></p>
  <% end %>
</div>
<% end %>

app/views/spree/admin/wholesalers/new.html.erb
<h1><%= t("new_wholesaler") %></h1>

<%= form_for [:admin, @wholesaler], :html => { :class => "wholesaler-form" } do |f| %>
  <%= render "spree/shared/error_messages", :target => @wholesaler %>
  <%= render "form", :form => f %>
  <%= render "spree/admin/shared/new_resource_links" %>
<% end %>

app/views/spree/admin/wholesalers/show.html.erb
<h1><%= t("wholesaler_account") %></h1>

<div class="leftie">

  <h5>Company:</h5>
  <h3><%= @wholesaler.company %></h3>

  <h5>Buyer_contact:</h5>
  <h3><%= @wholesaler.buyer_contact %></h3>

  <h5>Manager_contact:</h5>
  <h3><%= @wholesaler.manager_contact %></h3>

  <h5>Phone:</h5>
  <h3><%= @wholesaler.phone %></h3>

  <h5>Fax:</h5>
  <h3><%= @wholesaler.fax %></h3>

  <h5>Resale_number:</h5>
  <h3><%= @wholesaler.resale_number %></h3>

  <h5>Taxid:</h5>
  <h3><%= @wholesaler.taxid %></h3>

  <h5>Web_address:</h5>
  <h3><%= @wholesaler.web_address %></h3>

  <h5>Terms:</h5>
  <h3><%= @wholesaler.terms %></h3>

  <h5>Notes:</h5>
  <h3><%= simple_format @wholesaler.notes %></h3>

</div>

<div class="rightie">

  <div class="adr">
    <h4><%= t("bill_address") %></h4>
    <%= render 'spree/admin/shared/address', :address => @wholesaler.bill_address %>
  </div>
  <div class="adr">
    <h4><%= t("ship_address") %></h4>
    <%= render 'spree/admin/shared/address', :address => @wholesaler.ship_address %>
  </div>

  <div class="adr">
    <h4><%= t("user_details") %></h4>
    <p>
      ID: <%= @wholesaler.user.id %>
      <br/>
      Email: <%= @wholesaler.user.email %>
      <br/>
      <%= link_to "view user", admin_user_path(@wholesaler.user) %> /
      <%= link_to "edit user", edit_admin_user_path(@wholesaler.user) %> /
      <%= render "user_options", :user => @wholesaler.user %>
    </p>
  </div>

</div>

<hr/>

<p>
  <%= link_to_edit @wholesaler %> <%= t('or') %>
  <%= link_to t('back'), collection_url %>
</p>